[package]
name = "project5"
version = "0.1.0"
edition = "2024"

[dependencies]
imageproc = "0.25.0"
image = "0.25.6"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "bench_filter"
harness = false

[profile.dev]
opt-level = 3
overflow-checks = false
lto = true
debug = false